repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, master, --branch, main, --pattern, release/.*]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs

  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint linter
        language: system
        entry: env GOFLAGS="-tags=integration,e2e" go tool golangci-lint run --new-from-rev HEAD --fix --timeout=5m
        pass_filenames: false

      - id: golangci-lint-fmt
        name: golangci-lint formatter
        language: system
        entry: env GOFLAGS="-tags=integration,e2e" go tool golangci-lint fmt
        pass_filenames: false

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        args: [
          "--ignore", "body-is-missing", "--contrib=CT1", "--msg-filename",
        ]
        stages: [commit-msg]
