networks:
  paste-network:

volumes:
  paste:

services:
  paste:
    build:
      context: .
      dockerfile: Dockerfile

    image: 'thek4n/paste'

    pull_policy: build

    container_name: 'paste'

    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_started

    ports:
      - 8081:80

    networks:
      - paste-network

    environment:
      REDIS_HOST: 'paste-db'
      BROKER_HOST: 'paste-rabbitmq'

    restart: unless-stopped

    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

    healthcheck:
      test: ["CMD", "/app/ping", "--method", "json", "http://localhost:80/health/"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 1s
      start_interval: 3s

  db:
    image: redis
    container_name: 'paste-db'
    networks:
      - paste-network
    restart: unless-stopped
    volumes:
      - paste:/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 1s
      start_interval: 3s

  broker:
    image: rabbitmq
    container_name: 'paste-rabbitmq'
    networks:
      - paste-network
    restart: unless-stopped
